---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - security.joseberr.io
  resources:
  - wizcloudconfigurationrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.joseberr.io
  resources:
  - wizcloudconfigurationrules/finalizers
  verbs:
  - update
- apiGroups:
  - security.joseberr.io
  resources:
  - wizcloudconfigurationrules/status
  verbs:
  - get
  - patch
  - update
